[package]
name = "gnosis-vpn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
crossbeam-channel = "0.5.13"
ctrlc = "3.4.5"
env_logger = "0.11.5"
futures = "0.3.31"
gnosis-vpn-lib = { version = "0.1.0", path = "../gnosis-vpn-lib" }
log = "0.4.22"
reqwest = { version = "0.12.9", features = ["json", "blocking"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
url = "2.5.3"
