[package]
name = "gnosis-vpn-ctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
env_logger = "0.11.5"
gnosis-vpn-lib = { version = "0.1.0", path = "../gnosis-vpn-lib" }
tracing = "0.1.40"
url = "2.5.3"
