name: Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: self-hosted-hoprnet-bigger

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v29
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v15
      with:
        name: gnosis-vpn-client
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      env:
        USER: runner

    - name: Build
      run: nix build .#gnosisvpn -L

    - name: Lint and formatting check
      run: nix run .#check

    - name: Tests
      run: nix build .#gnosisvpn-test
