name: Merge PR
on:
  pull_request:
    types:
      - closed
      # - synchronize
    branches:
      - main
concurrency:
  group: merge
  cancel-in-progress: false
jobs:
  delete-artifacts:
    name: Delete artifacts
    runs-on: self-hosted-hoprnet-small
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup GCP
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@master
        with:
          google-credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
          install-sdk: "true"
      - name: Delete artifacts
        run: |
          set -x
          pr_version=$(grep -E '^version\s*=' Cargo.toml | awk -F\" '{print $2}')-pr.${{ github.event.pull_request.number }}
          echo "pr_version=$pr_version" >> ·GITHUB_OUTPUT
          gcloud config set artifacts/location europe-west3
          gcloud artifacts versions delete --quiet --repository="rust-binaries" --package=gnosis_vpn ${pr_version}  2> /dev/null || true
          gcloud artifacts versions delete --quiet --repository="rust-binaries" --package=gnosis_vpn ${pr_version}  2> /dev/null || true
  build-binaries:
    strategy:
      matrix:
        binary:
          - architecture: x86_64-linux-libc-2-40
            runner: self-hosted-hoprnet-big
          - architecture: x86_64-linux-libc-2-39
            runner: self-hosted-hoprnet-big
          - architecture: x86_64-linux-libc-2-38
            runner: self-hosted-hoprnet-big
          - architecture: aarch64-linux
            runner: self-hosted-hoprnet-big
          - architecture: armv7l-linux
            runner: self-hosted-hoprnet-big
          - architecture: aarch64-darwin
            runner: macos-14
          - architecture: x86_64-darwin
            runner: macos-13
    name: Binary ${{ matrix.binary.architecture }}
    needs:
      - delete-artifacts
    uses: ./.github/workflows/build-binaries.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      runner: ${{ matrix.binary.runner }}
      architecture: ${{ matrix.binary.architecture }}
      version_type: "pr"
    secrets: inherit
  comment:
    name: Comment PR
    runs-on: self-hosted-hoprnet-small
    needs:
      - build-binaries
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get version
        id: vars
        run: |
          set -x
          pr_version=$(grep -E '^version\s*=' Cargo.toml | awk -F\" '{print $2}')-pr.${{ github.event.pull_request.number }}
          echo "pr_version=$pr_version" >> $GITHUB_OUTPUT
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The binaries for this PR can be downloaded from:
            ```
            mkdir ./binaries
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-aarch64-linux --destination=./binaries --local-filename=gnosis_vpn-aarch64-linux
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-ctl-aarch64-linux --destination=./binaries --local-filename=gnosis_vpn-ctl-aarch64-linux

            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-x86_64-linux-libc-2-40 --destination=./binaries --local-filename=gnosis_vpn-x86_64-linux-libc-2-40
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-ctl-x86_64-linux-libc-2-40 --destination=./binaries --local-filename=gnosis_vpn-x86_64-linux-libc-2-40
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-x86_64-linux-libc-2-39 --destination=./binaries --local-filename=gnosis_vpn-x86_64-linux-libc-2-39
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-ctl-x86_64-linux-libc-2-39 --destination=./binaries --local-filename=gnosis_vpn-x86_64-linux-libc-2-39
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-x86_64-linux-libc-2-38 --destination=./binaries --local-filename=gnosis_vpn-x86_64-linux-libc-2-38
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-ctl-x86_64-linux-libc-2-38 --destination=./binaries --local-filename=gnosis_vpn-x86_64-linux-libc-2-38

            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-armv7l-linux --destination=./binaries --local-filename=gnosis_vpn-armv7l-linux
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-ctl-armv7l-linux --destination=./binaries --local-filename=gnosis_vpn-armv7l-linux

            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-aarch64-darwin --destination=./binaries --local-filename=gnosis_vpn-aarch64-darwin
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-ctl-aarch64-darwin --destination=./binaries --local-filename=gnosis_vpn-aarch64-darwin

            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-x86_64-darwin --destination=./binaries --local-filename=gnosis_vpn-x86_64-darwin
            gcloud artifacts files download --project=hoprassociation --location=europe-west3 --repository=rust-binaries gnosis_vpn:${{ steps.vars.outputs.pr_version }}:gnosis_vpn-ctl-x86_64-darwin --destination=./binaries --local-filename=gnosis_vpn-x86_64-darwin
            ```
